# Directories and Files
db_file           "~/.config/mpd/database"
log_file          "~/.config/mpd/log"
music_directory    "/home/ochinix/Music"
playlist_directory "~/.config/mpd/playlists"
pid_file          "~/.config/mpd/pid"
state_file        "~/.config/mpd/state"
sticker_file      "~/.config/mpd/sticker.sql"

# Network settings
bind_to_address   "0.0.0.0"  # Allows MPD to listen on all network interfaces
port              "6600"     # MPD control port

# General settings
restore_paused    "yes"
max_output_buffer_size "16384"
user               "ochinix"
auto_update       "yes"
follow_inside_symlinks "yes"

# Input plugins
input {
    plugin "curl"
}

# Audio output for local playback (Pulseaudio or PipeWire)
audio_output {
    type "pulse"  # For PipeWire, keep "pulse" here
    name "ALSA/Pulseaudio"
    mixer_type "software"
}

# FIFO for visualizers (optional)
audio_output {
    type   "fifo"
    name   "toggle_visualizer"
    path   "/tmp/mpd.fifo"
    format "44100:16:2"
}

# HTTP audio output (for streaming)
audio_output {
    type "httpd"
    name "My HTTP Stream"
    encoder "vorbis"          # You can use "vorbis" or "mp3"
    port "8000"               # Port for streaming
    bind_to_address "0.0.0.0" # Listen on all interfaces
#    quality "5.0"             # Adjust this for bitrate/quality
    bitrate    "128"
    format "44100:16:2"       # Standard format
    max_clients  "2"
}

# Decoder plugin settings
decoder {
    plugin "wildmidi"
    enabled "no"
}

# Symlink settings
follow_inside_symlinks "yes"

